/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lynn_Main */

#ifndef _Included_org_lynn_Main
#define _Included_org_lynn_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lynn_Main
 * Method:    helloworld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lynn_Main_helloworld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
